services:
  db:
    image: postgres:15
    container_name: docflow-db
    restart: always
    environment:
      - POSTGRES_USER=docflow
      - POSTGRES_PASSWORD=documentpass
      - POSTGRES_DB=docflow_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: docflow-mail
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build: .
    container_name: docflow-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mailhog
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docflow_db
      - SPRING_DATASOURCE_USERNAME=docflow
      - SPRING_DATASOURCE_PASSWORD=documentpass
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: